name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        # Aqui eu posso adicionar comandos para executar testes.
        echo "API funcionando"

    - name: Build Docker image
      run: docker build -t comments_api .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 comments_api
